export default {
  login: "Fomachka",
  id: 47694895,
  node_id: "MDQ6VXNlcjQ3Njk0ODk1",
  avatar_url: "https://avatars.githubusercontent.com/u/47694895?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Fomachka",
  html_url: "https://github.com/Fomachka",
  followers_url: "https://api.github.com/users/Fomachka/followers",
  following_url: "https://api.github.com/users/Fomachka/following{/other_user}",
  gists_url: "https://api.github.com/users/Fomachka/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Fomachka/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Fomachka/subscriptions",
  organizations_url: "https://api.github.com/users/Fomachka/orgs",
  repos_url: "https://api.github.com/users/Fomachka/repos",
  events_url: "https://api.github.com/users/Fomachka/events{/privacy}",
  received_events_url: "https://api.github.com/users/Fomachka/received_events",
  type: "User",
  site_admin: false,
  name: "Man Khi Kim",
  company: "OKSCOMPANY LIMITED",
  blog: "",
  location: "Seoul, South Korea",
  email: null,
  hireable: null,
  bio: "• MSc Computer Science from University of Birmingham\r\n• Professional Fullstack Developer \r\n• Proficient in Javascript, Java, C#, Unity Engine\r\n",
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-02-16T15:31:25Z",
  updated_at: "2021-08-02T08:51:44Z",
};
